### ISSUE TITLE
`rabbitmq_user`: ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by francoisfreitag** [ansible-collections/community.rabbitmq#47]
##### SUMMARY
Module `rabbitmq_user` crashes with message `ValueError: need more than 1 value to unpack`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.rabbitmq.rabbitmq_user`

##### ANSIBLE VERSION
```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/home/freitafr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/freitafr/dev/repr-rabbitmq/venv/lib/python3.8/site-packages/ansible
  executable location = /home/freitafr/dev/repr-rabbitmq/venv/bin/ansible
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
```

##### CONFIGURATION
```paste below
```

##### OS / ENVIRONMENT
Centos 7 (x86_64)

##### STEPS TO REPRODUCE

Create a virtual machine. I used the following [`Vagrantfile`](https://www.vagrantup.com/docs/vagrantfile)
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision :ansible do |ansible|
      ansible.playbook_command = "venv/bin/ansible-playbook"
      ansible.playbook = "rabbitmq.yml"
  end
end
```
Run the following playbook **twice**.

```yaml
---
- hosts: all
  tasks:
    - name: Install epel
      become: true
      yum:
        name: epel-release

    - name: Install RabbitMQ
      become: true
      yum:
        name: rabbitmq-server

    - name: Configure rabbitmq
      become: true
      copy:
        content: NODENAME=rabbit@localhost
        dest: /etc/rabbitmq/rabbitmq-env.conf
        mode: 0644

    - name: Start RabbitMQ
      become: true
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes

    # Running this playbook **twice** triggers the failure.
    - name: Remove guest user from rabbitmq
      become: true
      rabbitmq_user:
        user: guest
        state: absent
        node: rabbit@localhost
```

```shell
# Sequence of commands to produce the failure:
# 1. Copy Vagrantfile and rabbitmq.yml playbook in the same directory.
# Start the virtual machine, will provision it with the playbook a first time.
$ vagrant up
# Re-provision
$ vagrant provision
# See the crash.
```

##### EXPECTED RESULTS
Guest user is removed on first run. Task unchanged on second run.

##### ACTUAL RESULTS

An exception is raised by the module on second run:

```
File \"/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py\", line 431, in main
File \"/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py\", line 299, in get
ValueError: need more than 1 value to unpack\r\n
```

```paste below
TASK [Remove guest user from rabbitmq] *****************************************
task path: /home/freitafr/dev/repr-rabbitmq/rabbitmq.yml:23
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2205 -o 'IdentityFile="/home/freitafr/dev/repr-rabbitmq/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/freitafr/.ansible/cp/6776d839fb 127.0.0.1 '/bin/sh -c '"'"'echo ~vagrant && sleep 0'"'"''
<127.0.0.1> (0, b'/home/vagrant\n', b'OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2205 -o 'IdentityFile="/home/freitafr/dev/repr-rabbitmq/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/freitafr/.ansible/cp/6776d839fb 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128 `" && echo ansible-tmp-1605268884.2947245-99808-103654085490128="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128 `" ) && sleep 0'"'"''
<127.0.0.1> (0, b'ansible-tmp-1605268884.2947245-99808-103654085490128=/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128\n', b'OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
redirecting (type: modules) ansible.builtin.rabbitmq_user to community.rabbitmq.rabbitmq_user
Using module file /home/freitafr/dev/repr-rabbitmq/venv/lib/python3.8/site-packages/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py
<127.0.0.1> PUT /home/freitafr/.ansible/tmp/ansible-local-99747mcuoqykc/tmpv0hjrzce TO /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py
<127.0.0.1> SSH: EXEC sftp -b - -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2205 -o 'IdentityFile="/home/freitafr/dev/repr-rabbitmq/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/freitafr/.ansible/cp/6776d839fb '[127.0.0.1]'
<127.0.0.1> (0, b'sftp> put /home/freitafr/.ansible/tmp/ansible-local-99747mcuoqykc/tmpv0hjrzce /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py\n', b'OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension "posix-rename@openssh.com" revision 1\r\ndebug2: Server supports extension "statvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "fstatvfs@openssh.com" revision 2\r\ndebug2: Server supports extension "hardlink@openssh.com" revision 1\r\ndebug2: Server supports extension "fsync@openssh.com" revision 1\r\ndebug3: Sent message fd 3 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/vagrant size 0\r\ndebug3: Looking up /home/freitafr/.ansible/tmp/ansible-local-99747mcuoqykc/tmpv0hjrzce\r\ndebug3: Sent message fd 3 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn\'t stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py\r\ndebug3: Sent message SSH2_FXP_WRITE I:4 O:0 S:32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 4 32768 bytes at 0\r\ndebug3: Sent message SSH2_FXP_WRITE I:5 O:32768 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:6 O:65536 S:32768\r\ndebug3: Sent message SSH2_FXP_WRITE I:7 O:98304 S:22650\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 5 32768 bytes at 32768\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 6 32768 bytes at 65536\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: In write loop, ack for 7 22650 bytes at 98304\r\ndebug3: Sent message SSH2_FXP_CLOSE I:4\r\ndebug3: SSH2_FXP_STATUS 0\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2205 -o 'IdentityFile="/home/freitafr/dev/repr-rabbitmq/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/freitafr/.ansible/cp/6776d839fb 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/ /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py && sleep 0'"'"''
<127.0.0.1> (0, b'', b'OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2205 -o 'IdentityFile="/home/freitafr/dev/repr-rabbitmq/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/freitafr/.ansible/cp/6776d839fb -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-cwmrbhfnehddhwkaptdlfieroprszduh ; /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<127.0.0.1> (1, b'Traceback (most recent call last):\r\n  File "/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py", line 102, in <module>\r\n    _ansiballz_main()\r\n  File "/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py", line 40, in invoke_module\r\n    runpy.run_module(mod_name=\'ansible_collections.community.rabbitmq.plugins.modules.rabbitmq_user\', init_globals=None, run_name=\'__main__\', alter_sys=True)\r\n  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code\r\n    exec code in run_globals\r\n  File "/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py", line 463, in <module>\r\n  File "/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py", line 431, in main\r\n  File "/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py", line 299, in get\r\nValueError: need more than 1 value to unpack\r\n', b'OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 127.0.0.1 closed.\r\n')
<127.0.0.1> Failed to connect to the host via ssh: OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
debug1: Reading configuration data /home/freitafr/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug2: resolve_canonicalize: hostname 127.0.0.1 is address
debug1: auto-mux: Trying existing master
debug2: fd 3 setting O_NONBLOCK
debug2: mux_client_hello_exchange: master version 4
debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
debug3: mux_client_request_session: entering
debug3: mux_client_request_alive: entering
debug3: mux_client_request_alive: done pid = 99757
debug3: mux_client_request_session: session request sent
debug1: mux_client_request_session: master session id: 2
debug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 1
Shared connection to 127.0.0.1 closed.
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2205 -o 'IdentityFile="/home/freitafr/dev/repr-rabbitmq/.vagrant/machines/default/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/freitafr/.ansible/cp/6776d839fb 127.0.0.1 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/ > /dev/null 2>&1 && sleep 0'"'"''
<127.0.0.1> (0, b'', b'OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n')
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.rabbitmq.plugins.modules.rabbitmq_user', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py", line 463, in <module>
  File "/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py", line 431, in main
  File "/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py", line 299, in get
ValueError: need more than 1 value to unpack
fatal: [default]: FAILED! => {
    "changed": false,
    "module_stderr": "OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020\r\ndebug1: Reading configuration data /home/freitafr/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug2: resolve_canonicalize: hostname 127.0.0.1 is address\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 99757\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1605268884.2947245-99808-103654085490128/AnsiballZ_rabbitmq_user.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.rabbitmq.plugins.modules.rabbitmq_user', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py\", line 463, in <module>\r\n  File \"/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py\", line 431, in main\r\n  File \"/tmp/ansible_rabbitmq_user_payload_2cDtIG/ansible_rabbitmq_user_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_user.py\", line 299, in get\r\nValueError: need more than 1 value to unpack\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

### Additional details

The playbook in the steps to reproduce gives the expected results for `Ansible 2.9.15`.

**Comment by jdufresne** [comment]
I think this might have been fixed in 351d9fb11c09bc3f8f32992679c948a253226032.
