### ISSUE TITLE
rabbitmq_policy json.decoder error when trying to apply a policy

### ISSUE THREAD

**Issue by nazunalika** [ansible-collections/community.rabbitmq#57]
##### SUMMARY
When trying to apply a policy, a `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` error appears.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.rabbitmq.rabbitmq_policy`

##### ANSIBLE VERSION
```
ansible 2.9.16
  config file = /home/ansible/infrastructure/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION
```
ANSIBLE_FORCE_COLOR(/home/ansible/infrastructure/ansible/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/ansible/infrastructure/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ansible/infrastructure/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o GSSAPIAuthentication=no
CACHE_PLUGIN(/home/ansible/infrastructure/ansible/ansible.cfg) = memory
CACHE_PLUGIN_TIMEOUT(/home/ansible/infrastructure/ansible/ansible.cfg) = 1800
COLLECTIONS_PATHS(/home/ansible/infrastructure/ansible/ansible.cfg) = ['/home/ansible/infrastructure/ansible/collections']
COMMAND_WARNINGS(/home/ansible/infrastructure/ansible/ansible.cfg) = True
DEFAULT_FORKS(/home/ansible/infrastructure/ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/home/ansible/infrastructure/ansible/ansible.cfg) = smart
DEFAULT_LOG_PATH(/home/ansible/infrastructure/ansible/ansible.cfg) = /home/ansible/infrastructure/ansible/tmp/ansible.log
DEFAULT_MANAGED_STR(/home/ansible/infrastructure/ansible/ansible.cfg) = Ansible managed
DEFAULT_NO_LOG(/home/ansible/infrastructure/ansible/ansible.cfg) = False
DEFAULT_ROLES_PATH(/home/ansible/infrastructure/ansible/ansible.cfg) = ['/home/ansible/infrastructure/ansible/roles/local', '/home/ansible/infrastructure/ansible/roles/public']
DEFAULT_STRATEGY(/home/ansible/infrastructure/ansible/ansible.cfg) = free
DISPLAY_ARGS_TO_STDOUT(/home/ansible/infrastructure/ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/ansible/infrastructure/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ansible/infrastructure/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
CentOS 8.3, x86_64
RabbitMQ 3.8.3

##### STEPS TO REPRODUCE

Create a simple playbook with a set of tasks to create a virtual host and then apply a policy to the vhost.

```yaml
- name: Configure pubsub virtual host
  community.rabbitmq.rabbitmq_vhost:
    name: /pubsub
    state: present

- name: Configure an HA policy for pubsub
  community.rabbitmq.rabbitmq_policy:
    name: HA
    apply_to: queues
    pattern: ".*"
    tags:
      ha-mode: all
      ha-sync-mode: automatic
      ha-sync-batch-size: 10000
    vhost: /pubsub
```

##### EXPECTED RESULTS

Vhost is created and policy is successfully applied.

##### ACTUAL RESULTS

The playbook errors out with a module error.
```
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1611654783.6917102-146428-116716834350778/AnsiballZ_rabbitmq_policy.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1611654783.6917102-146428-116716834350778/AnsiballZ_rabbitmq_policy.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1611654783.6917102-146428-116716834350778/AnsiballZ_rabbitmq_policy.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.rabbitmq.plugins.modules.rabbitmq_policy', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py", line 248, in <module>
  File "/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py", line 237, in main
  File "/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py", line 161, in has_modifications
  File "/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py", line 161, in <genexpr>
  File "/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py", line 198, in _policy_check
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fatal: [ord1-prod-rabbitmq001.example.com]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 10.XX.XX.XX closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1611654783.6917102-146428-116716834350778/AnsiballZ_rabbitmq_policy.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1611654783.6917102-146428-116716834350778/AnsiballZ_rabbitmq_policy.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1611654783.6917102-146428-116716834350778/AnsiballZ_rabbitmq_policy.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.rabbitmq.plugins.modules.rabbitmq_policy', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py\", line 248, in <module>\r\n  File \"/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py\", line 237, in main\r\n  File \"/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py\", line 161, in has_modifications\r\n  File \"/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py\", line 161, in <genexpr>\r\n  File \"/tmp/ansible_community.rabbitmq.rabbitmq_policy_payload__4toqeqo/ansible_community.rabbitmq.rabbitmq_policy_payload.zip/ansible_collections/community/rabbitmq/plugins/modules/rabbitmq_policy.py\", line 198, in _policy_check\r\n  File \"/usr/lib64/python3.6/json/__init__.py\", line 354, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 339, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/lib64/python3.6/json/decoder.py\", line 357, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by nazunalika** [comment]
After some investigating... this should be changed.

```
-       tags = json.loads(policy_data[tags_fno])
+       tags = policy_data[tags_fno]

```

There is no json here at all. It's just a string. I'll see about opening a PR.

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.rabbitmq/pull/86
